# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Graph Neural Network Tutorials
author: Md Khairul Islam
email: khairulislam@virginia.edu
copyright: '2024'
logo: images/logo.jpeg
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files: true

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/khairulislam/GNN  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
  recursive_update: true
  config:
    language: en
    bibtex_reference_style: author_year  # or label, super, \supercite
    # unknown_mime_type - application/vnd.plotly.v1+json and application/vnd.bokehjs_load.v0+json
    # domains - sphinx_proof.domain::prf needs to have `resolve_any_xref` method
    # mime_priority - latex priority not set in myst_nb for text/html, application/javascript
    suppress_warnings: ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority", "myst-nb.lexer", "mystnb.lexer"]
    copybutton_prompt_text: "$"

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - amsmath
    - dollarmath